import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {getAdminStats,getAdminOrders,updateOrderStatus,getAdminProducts,getAdminUsers,createAdminProduct,updateAdminProduct,deleteAdminProduct} from '../services/api.js'
const statuses=['PLACED','CONFIRMED','PREPARING','OUT_FOR_DELIVERY','DELIVERED','CANCELLED']
const pretty=s=>({PLACED:'Order Placed',CONFIRMED:'Confirmed',PREPARING:'Preparing',OUT_FOR_DELIVERY:'Out for Delivery',DELIVERED:'Delivered',CANCELLED:'Cancelled'}[s]||s)
const blank={id:'',name:'',category:'',price:'',oldPrice:'',rating:'5',reviews:'0',badge:'',description:'',image:'',active:true}
export default function Admin(){
 const [tab,setTab]=useState('dashboard'),[stats,setStats]=useState(null),[orders,setOrders]=useState([]),[products,setProducts]=useState([]),[users,setUsers]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(false),[notice,setNotice]=useState('')
 async function load(){try{const [s,o,p,u]=await Promise.all([getAdminStats(),getAdminOrders(),getAdminProducts(),getAdminUsers()]);setStats(s);setOrders(o);setProducts(p);setUsers(u)}catch(e){setNotice(e.message)}} useEffect(()=>{load()},[])
 async function status(n,s){await updateOrderStatus(n,s);setNotice('Order status updated');load()}
 async function saveProduct(e){e.preventDefault();const payload={...form,price:Number(form.price),oldPrice:form.oldPrice?Number(form.oldPrice):null,rating:Number(form.rating),reviews:Number(form.reviews)};if(editing) await updateAdminProduct(form.id,payload);else await createAdminProduct(payload);setForm(blank);setEditing(false);setNotice('Product saved');load()}
 async function remove(id){if(confirm('Delete this product?')){await deleteAdminProduct(id);setNotice('Product deleted');load()}}
 return <div className="admin-shell"><aside className="admin-sidebar"><Link to="/" className="admin-brand">🍦 Icy<span>Tales</span></Link><div className="admin-caption">CONTROL CENTER</div>{[['dashboard','⌂','Dashboard'],['orders','◷','Orders'],['products','✦','Products'],['users','♙','Users']].map(([id,ic,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><i>{ic}</i>{label}</button>)}<Link to="/" className="back-store">← Back to store</Link></aside><main className="admin-main">
 <div className="admin-top"><div><span className="eyebrow">ICyTALES ADMIN</span><h1>{tab[0].toUpperCase()+tab.slice(1)}</h1></div><Link to="/" className="btn btn-outline btn-sm">View Store ↗</Link></div>{notice&&<div className="admin-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
 {tab==='dashboard'&&<><div className="stat-grid">{[['Users',stats?.totalUsers,'♙'],['Orders',stats?.totalOrders,'◷'],['Products',stats?.totalProducts,'✦'],['Revenue',`₹${Number(stats?.totalRevenue||0).toFixed(2)}`,'₹']].map(x=><div className="stat-card" key={x[0]}><span>{x[2]}</span><small>{x[0]}</small><strong>{x[1]??'—'}</strong></div>)}</div><div className="admin-panel"><div className="panel-head"><h2>Recent orders</h2><button onClick={()=>setTab('orders')}>View all →</button></div>{orders.slice(0,5).map(o=><div className="admin-order-row" key={o.orderNumber}><div><b>{o.orderNumber}</b><span>{o.firstName} {o.lastName} · {o.email}</span></div><strong>₹{Number(o.grandTotal).toFixed(2)}</strong><span className={`status-pill ${o.status.toLowerCase()}`}>{pretty(o.status)}</span></div>)}</div></>}
 {tab==='orders'&&<div className="admin-panel"><div className="panel-head"><h2>Order management</h2><span>{orders.length} total</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Total</th><th>Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.orderNumber}><td><b>{o.orderNumber}</b></td><td>{o.firstName} {o.lastName}<small>{o.email}</small></td><td>{o.createdAt?new Date(o.createdAt).toLocaleDateString():''}</td><td>₹{Number(o.grandTotal).toFixed(2)}</td><td><select value={o.status} onChange={e=>status(o.orderNumber,e.target.value)}>{statuses.map(s=><option key={s} value={s}>{pretty(s)}</option>)}</select></td></tr>)}</tbody></table></div></div>}
 {tab==='products'&&<div className="admin-products"><div className="admin-panel product-form-panel"><div className="panel-head"><h2>{editing?'Edit product':'Add product'}</h2>{editing&&<button onClick={()=>{setEditing(false);setForm(blank)}}>Cancel</button>}</div><form className="admin-product-form" onSubmit={saveProduct}>{[['id','Product ID'],['name','Name'],['category','Category'],['price','Price'],['oldPrice','Old Price'],['rating','Rating'],['reviews','Reviews'],['badge','Badge'],['image','Image path']].map(([k,l])=><label key={k}>{l}<input required={['id','name','category','price','image'].includes(k)} value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label className="full">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="btn btn-primary">{editing?'Update Product':'Add Product'}</button></form></div><div className="admin-panel"><div className="panel-head"><h2>Products</h2><span>{products.length} total</span></div><div className="product-admin-list">{products.map(p=><div className="product-admin-row" key={p.id}><img src={p.image} alt=""/><div><b>{p.name}</b><span>{p.category} · ₹{p.price}</span></div><button onClick={()=>{setForm({...p,oldPrice:p.oldPrice??'',rating:p.rating??5,reviews:p.reviews??0});setEditing(true);window.scrollTo({top:0,behavior:'smooth'})}}>Edit</button><button className="danger" onClick={()=>remove(p.id)}>Delete</button></div>)}</div></div></div>}
 {tab==='users'&&<div className="admin-panel"><div className="panel-head"><h2>Registered users</h2><span>{users.length} users</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Name</th><th>Email</th><th>User ID</th><th>Role</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.name}</b></td><td>{u.email}</td><td>{u.userId}</td><td><span className="role-pill">{u.role}</span></td></tr>)}</tbody></table></div></div>}
 </main></div>
}
