spring.application.name=icytales-backend

server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/icytales?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=9150218083
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Helpful during local development
spring.jpa.open-in-view=false